name: PlannerAPI CI/CD

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "6.0.x"
  AZURE_WEBAPP_NAME: anteater-pathway-planner-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Setup .NET 6 ğŸ”§
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Retore dependencies ğŸ› ï¸
        working-directory: ./PlannerAPI/
        run: dotnet restore

      - name: Build app ğŸš€
        working-directory: ./PlannerAPI/
        run: dotnet build -c Release --no-restore

      - name: Run automated tests ğŸ§ª
        working-directory: ./PlannerAPI/
        run: dotnet test -c Release --no-build

      - name: Publish app ğŸ“°
        working-directory: ./PlannerAPI/PlannerAPI/
        run: dotnet publish -c Release -o ./out

      - name: Deploy to Azure Web Apps ğŸš¢
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_SECRET }}
          package: ./PlannerAPI/PlannerAPI/out/
