name: PlannerAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Setup .NET 6 ğŸ”§
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Retore dependencies ğŸ› ï¸
        working-directory: ./PlannerAPI/
        run: dotnet restore

      - name: Build app ğŸš€
        working-directory: ./PlannerAPI/
        run: dotnet build -c Release --no-restore

      - name: Run automated tests ğŸ§ª
        working-directory: ./PlannerAPI/
        run: dotnet test -c Release --no-build
